import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  Table,
  TableRow,
  TableCell,
  WidthType,
  VerticalAlign,
  ShadingType,
  type FileChild,
} from "docx";
import { jsPDF } from "jspdf";
import { saveAs } from "file-saver";

type ExportWord = Pick<
  VocabularyWord,
  | "word"
  | "syllabification"
  | "partOfSpeech"
  | "englishDefinition"
  | "chineseDefinition"
  | "example"
>;

function renderTextAsImage(
  pdf: jsPDF,
  text: string,
  x: number,
  y: number,
  maxWidth: number,
  fontSize: number,
  color: string,
  align: "left" | "center" | "right"
): void {
  const scale = 4;
  const canvas = document.createElement("canvas");
  const ctx = canvas.getContext("2d");
  if (!ctx) return;

  ctx.font = `${fontSize * scale}px "Noto Sans TC", "Microsoft JhengHei", "PingFang TC", sans-serif`;
  const lines: string[] = [];
  for (const line of text.split("\n")) {
    const words = [...line];
    let current = "";
    for (const char of words) {
      const test = current + char;
      if (ctx.measureText(test).width > maxWidth * scale) {
        lines.push(current);
        current = char;
      } else {
        current = test;
      }
    }
    if (current) lines.push(current);
  }

  const lineH = fontSize * scale * 1.3;
  const textW = maxWidth * scale;
  const textH = lines.length * lineH + lineH * 0.5;
  canvas.width = Math.ceil(textW);
  canvas.height = Math.ceil(textH);

  ctx.font = `${fontSize * scale}px "Noto Sans TC", "Microsoft JhengHei", "PingFang TC", sans-serif`;
  ctx.fillStyle = color;
  ctx.textBaseline = "top";

  for (let i = 0; i < lines.length; i++) {
    let drawX = 0;
    if (align === "center") {
      drawX = (textW - ctx.measureText(lines[i]).width) / 2;
    } else if (align === "right") {
      drawX = textW - ctx.measureText(lines[i]).width;
    }
    ctx.fillText(lines[i], drawX, i * lineH + lineH * 0.2);
  }

  const dataUrl = canvas.toDataURL("image/png");
  const imgW = maxWidth;
  const imgH = textH / scale;
  pdf.addImage(dataUrl, "PNG", x - (align === "center" ? imgW / 2 : align === "right" ? imgW : 0), y, imgW, imgH);
}

function formatDate(): string {
  return new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function titleParagraph(text: string): Paragraph {
  return new Paragraph({
    text,
    heading: HeadingLevel.TITLE,
    alignment: AlignmentType.CENTER,
  });
}

function subtitleParagraph(text: string): Paragraph {
  return new Paragraph({
    children: [
      new TextRun({
        text,
        italics: true,
        color: "595959",
      }),
    ],
    alignment: AlignmentType.CENTER,
    spacing: { after: 400 },
  });
}

export async function exportGlossaryDocx(
  words: ExportWord[],
  title?: string
): Promise<void> {
  const docTitle = title || "My Vocabulary Glossary";
  const date = formatDate();

  const children: FileChild[] = [];
  children.push(titleParagraph(docTitle));
  children.push(
    subtitleParagraph(`Generated by Mr.\uD83C\uDD96 ProReader on ${date}`)
  );

  const sorted = [...words].sort((a, b) => a.word.localeCompare(b.word));

  const headerRow = new TableRow({
    tableHeader: true,
    children: [
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: "#", bold: true })] })],
        width: { size: 5, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.SOLID, color: "E5E7EB" },
        verticalAlign: VerticalAlign.CENTER,
      }),
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: "Word", bold: true })] })],
        width: { size: 18, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.SOLID, color: "E5E7EB" },
        verticalAlign: VerticalAlign.CENTER,
      }),
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: "PoS", bold: true })] })],
        width: { size: 8, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.SOLID, color: "E5E7EB" },
        verticalAlign: VerticalAlign.CENTER,
      }),
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: "English Definition", bold: true })] })],
        width: { size: 30, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.SOLID, color: "E5E7EB" },
        verticalAlign: VerticalAlign.CENTER,
      }),
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: "Chinese Definition", bold: true })] })],
        width: { size: 22, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.SOLID, color: "E5E7EB" },
        verticalAlign: VerticalAlign.CENTER,
      }),
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: "Example", bold: true })] })],
        width: { size: 17, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.SOLID, color: "E5E7EB" },
        verticalAlign: VerticalAlign.CENTER,
      }),
    ],
  });

  const dataRows = sorted.map(
    (w, i) =>
      new TableRow({
        children: [
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: `${i + 1}` })] })],
            verticalAlign: VerticalAlign.CENTER,
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [
                  new TextRun({ text: w.word, bold: true }),
                ],
              }),
              ...(w.syllabification
                ? [new Paragraph({
                    children: [
                      new TextRun({ text: w.syllabification, color: "666666", size: 18 }),
                    ],
                    spacing: { before: 20 },
                  })]
                : []),
            ],
            verticalAlign: VerticalAlign.CENTER,
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [new TextRun({ text: w.partOfSpeech || "-", italics: true, color: "666666" })],
              }),
            ],
            verticalAlign: VerticalAlign.CENTER,
          }),
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: w.englishDefinition })] })],
            verticalAlign: VerticalAlign.CENTER,
          }),
          new TableCell({
            children: [new Paragraph({ children: [new TextRun({ text: w.chineseDefinition })] })],
            verticalAlign: VerticalAlign.CENTER,
          }),
          new TableCell({
            children: [
              new Paragraph({
                children: [
                  new TextRun({ text: w.example || "-", italics: true, color: "444444" }),
                ],
              }),
            ],
            verticalAlign: VerticalAlign.CENTER,
          }),
        ],
      })
  );

  const table = new Table({
    rows: [headerRow, ...dataRows],
    width: { size: 100, type: WidthType.PERCENTAGE },
  });

  children.push(table);

  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Total: ${words.length} words`,
          color: "666666",
          size: 18,
        }),
      ],
      spacing: { before: 300 },
    })
  );

  const doc = new Document({
    sections: [{ children }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `vocabulary-glossary-${Date.now()}.docx`);
}

export async function exportFlashcardPdf(
  words: ExportWord[]
): Promise<void> {
  const pdf = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });

  const pageW = 297;
  const pageH = 210;
  const margin = 10;
  const cols = 4;
  const rows = 2;
  const cardW = (pageW - margin * 2 - (cols - 1) * 4) / cols;
  const cardH = (pageH - margin * 2 - (rows - 1) * 4) / rows;
  const cornerR = 3;

  let cardIndex = 0;

  for (const w of words) {
    if (cardIndex % (cols * rows) === 0) {
      if (cardIndex > 0) pdf.addPage();
      drawCutLines(
        pdf,
        margin,
        margin,
        pageW - margin * 2,
        pageH - margin * 2,
        cols,
        rows,
        cardW,
        cardH
      );
    }

    const col = cardIndex % cols;
    const row = Math.floor((cardIndex % (cols * rows)) / cols);
    const x = margin + col * (cardW + 4);
    const y = margin + row * (cardH + 4);

    pdf.setDrawColor(200, 200, 200);
    pdf.setLineWidth(0.5);
    pdf.roundedRect(x, y, cardW, cardH, cornerR, cornerR);

    const midY = y + cardH / 2;
    pdf.setDrawColor(220, 220, 220);
    pdf.setLineDashPattern([3, 2], 0);
    pdf.line(x + 2, midY, x + cardW - 2, midY);
    pdf.setLineDashPattern([], 0);

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(16);
    const wordLines = pdf.splitTextToSize(w.word, cardW - 10);
    const wordLineH = 7;
    const topPad = 10;
    let topCursorY = y + topPad;
    pdf.text(wordLines, x + cardW / 2, topCursorY, {
      align: "center",
    });
    topCursorY += wordLines.length * wordLineH;

    if (w.syllabification) {
      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(9);
      pdf.setTextColor(100, 100, 100);
      pdf.text(w.syllabification, x + cardW / 2, topCursorY, {
        align: "center",
      });
      topCursorY += 4;
    }

    if (w.partOfSpeech) {
      pdf.setFont("helvetica", "italic");
      pdf.setFontSize(8);
      pdf.setTextColor(120, 120, 120);
      pdf.text(w.partOfSpeech, x + cardW / 2, topCursorY, {
        align: "center",
      });
    }

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(80, 80, 80);
    const enDefLines = pdf.splitTextToSize(
      w.englishDefinition,
      cardW - 10
    );
    const enDefBlockH = enDefLines.length * 4;
    const enDefY = midY + 10;
    pdf.text(enDefLines, x + cardW / 2, enDefY, {
      align: "center",
    });

    if (w.chineseDefinition) {
      pdf.setFontSize(5);
      pdf.setTextColor(100, 100, 100);
      const zhDefLines = pdf.splitTextToSize(
        w.chineseDefinition,
        cardW - 10
      );
      const zhY = enDefY + enDefBlockH + 2;
      renderTextAsImage(
        pdf,
        zhDefLines.join("\n"),
        x + cardW / 2,
        zhY,
        cardW - 10,
        5,
        "#64748b",
        "center"
      );
    }

    pdf.setTextColor(0, 0, 0);
    cardIndex++;
  }

  pdf.save(`vocabulary-flashcards-${Date.now()}.pdf`);
}

function drawCutLines(
  pdf: jsPDF,
  mx: number,
  my: number,
  areaW: number,
  areaH: number,
  cols: number,
  rows: number,
  cardW: number,
  cardH: number,
  gap: number = 4
) {
  pdf.setDrawColor(180, 180, 180);
  pdf.setLineWidth(0.2);
  pdf.setLineDashPattern([2, 2], 0);

  for (let c = 1; c < cols; c++) {
    const x = mx + c * (cardW + gap) - gap / 2;
    pdf.line(x, my - 2, x, my + areaH + 2);
  }
  for (let r = 1; r < rows; r++) {
    const y = my + r * (cardH + gap) - gap / 2;
    pdf.line(mx - 2, y, mx + areaW + 2, y);
  }

  pdf.setLineDashPattern([], 0);
}

export async function exportFillInBlankDocx(
  words: ExportWord[],
  title?: string
): Promise<void> {
  const docTitle = title || "Fill-in-the-Blank Worksheet";
  const date = formatDate();

  const children: FileChild[] = [];
  children.push(titleParagraph(docTitle));
  children.push(
    subtitleParagraph(`Generated by Mr.\uD83C\uDD96 ProReader on ${date}`)
  );

  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "Name: ___________________________     Date: _______________     Score: _______ / ",
        }),
        new TextRun({ text: `${words.length}`, bold: true }),
      ],
      spacing: { after: 400 },
    })
  );

  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "Instructions: Fill in the blank with the correct word from the Word Bank.",
        }),
      ],
      spacing: { after: 300 },
    })
  );

  const shuffled = [...words].sort(() => Math.random() - 0.5);

  children.push(
    new Paragraph({
      children: [new TextRun({ text: "Word Bank:", bold: true, underline: {} })],
      spacing: { before: 200, after: 100 },
    })
  );

  const bankWords = shuffled.map((w) => w.word).join("     ");
  children.push(
    new Paragraph({
      children: [new TextRun({ text: bankWords, size: 22 })],
      spacing: { after: 400 },
    })
  );

  for (let i = 0; i < words.length; i++) {
    const w = words[i];
    const example = w.example || `${w.englishDefinition}.`;
    const blanked = example.replace(
      new RegExp(`\\b${w.word.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "i"),
      "_______________"
    );

    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: `${i + 1}. `, bold: true }),
          new TextRun({ text: blanked || `_______________ (${w.partOfSpeech})` }),
        ],
        spacing: { before: 200, after: 80 },
      })
    );

    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: `Hint: `, italics: true, color: "888888" }),
          new TextRun({ text: w.englishDefinition, italics: true, color: "888888" }),
        ],
        spacing: { after: 200 },
      })
    );
  }

  children.push(
    new Paragraph({ text: "", spacing: { before: 600 } })
  );
  children.push(
    new Paragraph({
      children: [new TextRun({ text: "--- Answer Key ---", bold: true, color: "999999" })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 200, after: 200 },
    })
  );

  for (let i = 0; i < words.length; i++) {
    const w = words[i];
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: `${i + 1}. `, color: "999999" }),
          new TextRun({ text: w.word, bold: true, color: "22C55E" }),
          new TextRun({ text: ` — ${w.englishDefinition}`, color: "999999" }),
        ],
        spacing: { after: 60 },
      })
    );
  }

  const doc = new Document({
    sections: [{ children }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `fill-in-the-blank-${Date.now()}.docx`);
}

export async function exportMatchingDocx(
  words: ExportWord[],
  title?: string
): Promise<void> {
  const docTitle = title || "Matching Exercise";
  const date = formatDate();

  const children: FileChild[] = [];
  children.push(titleParagraph(docTitle));
  children.push(
    subtitleParagraph(`Generated by Mr.\uD83C\uDD96 ProReader on ${date}`)
  );

  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "Name: ___________________________     Date: _______________     Score: _______ / ",
        }),
        new TextRun({ text: `${words.length}`, bold: true }),
      ],
      spacing: { after: 400 },
    })
  );

  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "Instructions: Match each word in Column A with its correct definition in Column B. Write the letter of the correct definition next to each number.",
        }),
      ],
      spacing: { after: 400 },
    })
  );

  const shuffledDefs = [...words].sort(() => Math.random() - 0.5);
  const letterLabels = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

  const numCol = new TableCell({
    children: [new Paragraph({ children: [new TextRun({ text: "", bold: true })] })],
    width: { size: 5, type: WidthType.PERCENTAGE },
    shading: { type: ShadingType.SOLID, color: "E5E7EB" },
  });
  const wordCol = new TableCell({
    children: [new Paragraph({ children: [new TextRun({ text: "Column A: Word", bold: true })] })],
    width: { size: 35, type: WidthType.PERCENTAGE },
    shading: { type: ShadingType.SOLID, color: "E5E7EB" },
  });
  const ansCol = new TableCell({
    children: [new Paragraph({ children: [new TextRun({ text: "Ans", bold: true })] })],
    width: { size: 8, type: WidthType.PERCENTAGE },
    shading: { type: ShadingType.SOLID, color: "E5E7EB" },
  });
  const letterCol = new TableCell({
    children: [new Paragraph({ children: [new TextRun({ text: "", bold: true })] })],
    width: { size: 5, type: WidthType.PERCENTAGE },
    shading: { type: ShadingType.SOLID, color: "E5E7EB" },
  });
  const defCol = new TableCell({
    children: [new Paragraph({ children: [new TextRun({ text: "Column B: Definition", bold: true })] })],
    width: { size: 47, type: WidthType.PERCENTAGE },
    shading: { type: ShadingType.SOLID, color: "E5E7EB" },
  });

  const headerRow = new TableRow({
    tableHeader: true,
    children: [numCol, wordCol, ansCol, letterCol, defCol],
  });

  const dataRows = words.map((w, i) => {
    return new TableRow({
      children: [
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: `${i + 1}.` })] })],
          verticalAlign: VerticalAlign.CENTER,
        }),
        new TableCell({
          children: [
            new Paragraph({
              children: [
                new TextRun({ text: w.word, bold: true }),
                ...(w.partOfSpeech
                  ? [new TextRun({ text: ` (${w.partOfSpeech})`, italics: true, color: "666666", size: 18 })]
                  : []),
              ],
            }),
          ],
          verticalAlign: VerticalAlign.CENTER,
        }),
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: "___" })] })],
          verticalAlign: VerticalAlign.CENTER,
        }),
        new TableCell({
          children: [
            new Paragraph({ children: [new TextRun({ text: `${letterLabels[i]}.` })] }),
          ],
          verticalAlign: VerticalAlign.CENTER,
        }),
        new TableCell({
          children: [
            new Paragraph({
              children: [new TextRun({ text: shuffledDefs[i].englishDefinition })],
            }),
          ],
          verticalAlign: VerticalAlign.CENTER,
        }),
      ],
    });
  });

  const table = new Table({
    rows: [headerRow, ...dataRows],
    width: { size: 100, type: WidthType.PERCENTAGE },
  });

  children.push(table);

  children.push(
    new Paragraph({ text: "", spacing: { before: 600 } })
  );
  children.push(
    new Paragraph({
      children: [new TextRun({ text: "--- Answer Key ---", bold: true, color: "999999" })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 200, after: 200 },
    })
  );

  for (let i = 0; i < words.length; i++) {
    const w = words[i];
    const defIndex = shuffledDefs.indexOf(w);
    const letter = letterLabels[defIndex] || "?";
    children.push(
      new Paragraph({
        children: [
          new TextRun({ text: `${i + 1}. `, color: "999999" }),
          new TextRun({ text: w.word, bold: true, color: "22C55E" }),
          new TextRun({ text: ` → ${letter}`, bold: true, color: "3B82F6" }),
          new TextRun({ text: ` — ${w.englishDefinition}`, color: "999999" }),
        ],
        spacing: { after: 60 },
      })
    );
  }

  const doc = new Document({
    sections: [{ children }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `matching-exercise-${Date.now()}.docx`);
}
